package com.maptanim.app.domain.repository

import com.maptanim.app.domain.model.*
import kotlinx.coroutines.flow.Flow

// ─── FarmRepository ────────────────────────────────────────────────────────

/**
 * Contract for farm data operations.
 * Implementation in data/repository/FarmRepositoryImpl.kt
 * All reads return Flow from Room (offline-first).
 * All writes go to Room first, then enqueue to SyncQueue.
 */
interface FarmRepository {
    fun observeFarms(farmerId: String): Flow<List<Farm>>
    fun observeFarm(farmId: String): Flow<Farm?>
    suspend fun upsertFarm(farm: Farm)
    suspend fun deleteFarm(farmId: String)
}

// ─── BedRepository ─────────────────────────────────────────────────────────

/**
 * Contract for bed (planting plot) data operations.
 * Source of truth: Room DB (synced from Supabase beds table).
 * Write path: Room → SyncQueue → SyncWorker → Supabase PATCH/POST/DELETE.
 */
interface BedRepository {
    /** Live stream of all active beds for a farm. Sourced from Room. */
    fun observeBeds(farmId: String): Flow<List<Bed>>

    /** Live stream of a single bed by ID. */
    fun observeBed(bedId: String): Flow<Bed?>

    /** Observe all beds across all farms for the current farmer (used by Calendar). */
    fun observeAllBedsWithCrop(farmerId: String): Flow<List<Bed>>

    /**
     * Persist updated beds (positions, soil, crop) to Room and enqueue sync.
     * Called by SaveFarmLayoutUseCase after SAVE CHANGES in Edit Mode.
     */
    suspend fun saveBeds(beds: List<Bed>)

    /** Soft-delete a bed (isActive = false) and enqueue Supabase DELETE. */
    suspend fun deleteBed(bedId: String)

    /** Upsert a single bed (used after Add Bed in Edit Mode). */
    suspend fun upsertBed(bed: Bed)
}

// ─── TaskRepository ────────────────────────────────────────────────────────

/**
 * Contract for DSS-generated task data.
 * Tasks are generated by the evaluate-dss Edge Function and stored in Supabase tasks table,
 * then synced to Room by SyncWorker / AppInitializationController.
 */
interface TaskRepository {
    /** Today's incomplete tasks for a farm. Drives TODAY'S TASKS panel and status pins. */
    fun observeTodayTasks(farmId: String, today: String): Flow<List<FarmTask>>

    /** All tasks for all farms owned by the farmer (used by Calendar screen). */
    fun observeAllTasks(farmerId: String): Flow<List<FarmTask>>

    /** Tasks within a date range (Calendar monthly view). */
    fun observeTasksForRange(farmerId: String, startDate: String, endDate: String): Flow<List<FarmTask>>

    /** Active alerts (PEST_ALERT, WARNING) — drives FARM SUMMARY "Active Alerts" count. */
    fun observeActiveAlerts(farmId: String): Flow<List<FarmTask>>

    /** HARVEST tasks — drives "Ready to Harvest" count in FARM SUMMARY. */
    fun observeHarvestReady(farmId: String): Flow<List<FarmTask>>

    /** Mark a task as completed. Updates Room immediately, enqueues Supabase PATCH. */
    suspend fun completeTask(taskId: String, completedAt: String)

    /** Upsert tasks received from evaluate-dss Edge Function response. */
    suspend fun upsertTasks(tasks: List<FarmTask>)
}

// ─── CropRepository ────────────────────────────────────────────────────────

/**
 * Contract for crop reference data.
 * Static reference — populated from Supabase crops table on first app launch.
 * Never user-editable in the mobile app (admin-only via Admin Dashboard).
 */
interface CropRepository {
    fun observeAllCrops(): Flow<List<Crop>>
    fun observeCropByName(name: String): Flow<Crop?>
    suspend fun upsertCrops(crops: List<Crop>)
}

// ─── NotificationRepository ────────────────────────────────────────────────

/**
 * Contract for notification data.
 * The notification badge count (e.g., "3" in the top bar) is driven by
 * observeUnreadCount() — never a hardcoded value.
 */
interface NotificationRepository {
    fun observeAllNotifications(userId: String): Flow<List<Notification>>

    /** Drives the 🔔 badge count in the top bar. Emits live count from Room. */
    fun observeUnreadCount(userId: String): Flow<Int>

    suspend fun markRead(notificationId: String)
    suspend fun markAllRead(userId: String)
    suspend fun upsertNotifications(notifications: List<Notification>)
}

// ─── HarvestRepository ─────────────────────────────────────────────────────

interface HarvestRepository {
    fun observeHarvestRecords(farmId: String): Flow<List<HarvestRecord>>
    suspend fun recordHarvest(record: HarvestRecord)
}

// ─── ActivityRepository ────────────────────────────────────────────────────

interface ActivityRepository {
    fun observeActivities(bedId: String): Flow<List<Activity>>
    suspend fun logActivity(activity: Activity)
}

// ─── SyncRepository ────────────────────────────────────────────────────────

/**
 * Contract for the offline sync queue.
 * SyncWorker reads from this repository to determine pending Supabase operations.
 */
interface SyncRepository {
    suspend fun enqueueSyncItem(tableName: String, recordId: String, operation: String, payload: String)
    suspend fun getPendingItems(): List<SyncQueueItem>
    suspend fun markSynced(itemId: String)
    suspend fun markFailed(itemId: String, lastAttemptAt: String)
    suspend fun hasPendingItems(): Boolean
}

data class SyncQueueItem(
    val id: String,
    val tableName: String,
    val recordId: String,
    val operation: String,  // "INSERT" | "UPDATE" | "DELETE"
    val payload: String,    // JSON
    val status: String,
    val attemptCount: Int
)

// ─── CropZoneRepository ───────────────────────────────────────────────────

interface CropZoneRepository {
    fun observeZonesByBedId(bedId: String): Flow<List<CropZone>>
    fun observeZonesByBedIds(bedIds: List<String>): Flow<List<CropZone>>
    suspend fun saveZones(zones: List<CropZone>)
    suspend fun deleteZone(zoneId: String)
}

// ─── FarmObjectRepository ─────────────────────────────────────────────────

interface FarmObjectRepository {
    fun observeObjectsByFarmId(farmId: String): Flow<List<FarmObject>>
    suspend fun saveObjects(objects: List<FarmObject>)
    suspend fun deleteObject(objectId: String)
}

