package com.maptanim.app.domain.usecase

import com.maptanim.app.domain.model.*
import com.maptanim.app.domain.repository.*
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.combine

// ─── Home Screen Use Cases ─────────────────────────────────────────────────

/**
 * Returns a live stream of today's tasks for a farm.
 * Drives the TODAY'S TASKS panel (left panel, View Mode).
 * Data source: TaskDao.observeTodayTasks() → Room → Supabase tasks table.
 * No hardcoded task list — every task was generated by evaluate-dss Edge Function.
 */
class GetTodayTasksUseCase(
    private val taskRepository: TaskRepository
) {
    operator fun invoke(farmId: String, today: String): Flow<List<FarmTask>> =
        taskRepository.observeTodayTasks(farmId, today)
}

/**
 * Returns a live aggregated FarmSummary.
 * Drives the FARM SUMMARY panel (Beds count, Plants count, Ready to Harvest, Active Alerts).
 * All 4 values computed from Room DB — never hardcoded.
 */
class GetFarmSummaryUseCase(
    private val bedRepository: BedRepository,
    private val taskRepository: TaskRepository
) {
    operator fun invoke(farmId: String): Flow<FarmSummary> = combine(
        bedRepository.observeBeds(farmId),
        taskRepository.observeHarvestReady(farmId),
        taskRepository.observeActiveAlerts(farmId)
    ) { beds, harvestReady, alerts ->
        FarmSummary(
            totalBeds = beds.size,
            totalPlants = beds.sumOf { estimatePlantCount(it) },
            readyToHarvest = harvestReady.size,
            activeAlerts = alerts.size
        )
    }

    /** Estimates plant count from bed area and crop density. No hardcoded counts. */
    private fun estimatePlantCount(bed: Bed): Int {
        val areaSqm = bed.widthM * bed.heightM
        return (areaSqm / 0.5f).toInt().coerceAtLeast(1)
    }
}

/**
 * Returns a live stream of all active beds for the farm canvas.
 * Drives isometric canvas rendering — bed positions, soil, crop come from Room.
 */
class GetFarmBedsUseCase(
    private val bedRepository: BedRepository
) {
    operator fun invoke(farmId: String): Flow<List<Bed>> =
        bedRepository.observeBeds(farmId)
}

// ─── Edit Mode Use Cases ───────────────────────────────────────────────────

/**
 * Persists the full set of edited beds after SAVE CHANGES is tapped.
 */
class SaveFarmLayoutUseCase(
    private val bedRepository: BedRepository,
    private val syncRepository: SyncRepository
) {
    suspend operator fun invoke(beds: List<Bed>) {
        bedRepository.saveBeds(beds)
    }
}

/**
 * Soft-deletes a bed from the farm layout.
 */
class DeleteBedUseCase(
    private val bedRepository: BedRepository
) {
    suspend operator fun invoke(bedId: String) =
        bedRepository.deleteBed(bedId)
}

/**
 * Inserts a new bed created in Edit Mode (Add Bed tool).
 */
class AddBedUseCase(
    private val bedRepository: BedRepository
) {
    suspend operator fun invoke(bed: Bed) =
        bedRepository.upsertBed(bed)
}

// ─── Notification Use Cases ────────────────────────────────────────────────

class GetUnreadNotificationCountUseCase(
    private val notificationRepository: NotificationRepository
) {
    operator fun invoke(userId: String): Flow<Int> =
        notificationRepository.observeUnreadCount(userId)
}

class GetNotificationsUseCase(
    private val notificationRepository: NotificationRepository
) {
    operator fun invoke(userId: String): Flow<List<Notification>> =
        notificationRepository.observeAllNotifications(userId)
}

class MarkNotificationReadUseCase(
    private val notificationRepository: NotificationRepository
) {
    suspend operator fun invoke(notificationId: String) =
        notificationRepository.markRead(notificationId)
}

// ─── Calendar Use Cases ────────────────────────────────────────────────────

class GetAllTasksUseCase(
    private val taskRepository: TaskRepository
) {
    operator fun invoke(farmerId: String): Flow<List<FarmTask>> =
        taskRepository.observeAllTasks(farmerId)
}

class GetTasksForDateRangeUseCase(
    private val taskRepository: TaskRepository
) {
    operator fun invoke(farmerId: String, startDate: String, endDate: String): Flow<List<FarmTask>> =
        taskRepository.observeTasksForRange(farmerId, startDate, endDate)
}

class CompleteTaskUseCase(
    private val taskRepository: TaskRepository
) {
    suspend operator fun invoke(taskId: String, completedAt: String) =
        taskRepository.completeTask(taskId, completedAt)
}

// ─── Library Use Cases ─────────────────────────────────────────────────────

class GetAllCropsUseCase(
    private val cropRepository: CropRepository
) {
    operator fun invoke(): Flow<List<Crop>> =
        cropRepository.observeAllCrops()
}

class GetCropByNameUseCase(
    private val cropRepository: CropRepository
) {
    operator fun invoke(name: String): Flow<Crop?> =
        cropRepository.observeCropByName(name)
}

// ─── Farm Management Use Cases ─────────────────────────────────────────────

class GetFarmsUseCase(
    private val farmRepository: FarmRepository
) {
    operator fun invoke(farmerId: String): Flow<List<Farm>> =
        farmRepository.observeFarms(farmerId)
}

// ─── Harvest Use Cases ─────────────────────────────────────────────────────

class RecordHarvestUseCase(
    private val harvestRepository: HarvestRepository
) {
    suspend operator fun invoke(record: HarvestRecord) =
        harvestRepository.recordHarvest(record)
}
