package com.maptanim.app.domain.usecase

import com.maptanim.app.domain.model.*
import com.maptanim.app.domain.repository.*
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.combine

// ─── Home Screen Use Cases ─────────────────────────────────────────────────

/**
 * Returns a live stream of today's tasks for a farm.
 * Drives the TODAY'S TASKS panel (left panel, View Mode).
 * Data source: TaskDao.observeTodayTasks() → Room → Supabase tasks table.
 * No hardcoded task list — every task was generated by evaluate-dss Edge Function.
 */
class GetTodayTasksUseCase(
    private val taskRepository: TaskRepository
) {
    operator fun invoke(farmId: String, today: String): Flow<List<FarmTask>> =
        taskRepository.observeTodayTasks(farmId, today)
}

/**
 * Returns a live aggregated FarmSummary.
 * Drives the FARM SUMMARY panel (Plots count, Plants count, Ready to Harvest, Active Alerts).
 * All 4 values computed from Room DB — never hardcoded.
 */
class GetFarmSummaryUseCase(
    private val plotRepository: CropPlotRepository,
    private val taskRepository: TaskRepository
) {
    operator fun invoke(farmId: String): Flow<FarmSummary> = combine(
        plotRepository.observePlots(farmId),
        taskRepository.observeHarvestReady(farmId),
        taskRepository.observeActiveAlerts(farmId)
    ) { plots, harvestReady, alerts ->
        FarmSummary(
            totalPlots = plots.size,
            totalPlants = plots.sumOf { estimatePlantCount(it) },
            readyToHarvest = harvestReady.size,
            activeAlerts = alerts.size
        )
    }

    /** Estimates plant count from plot area and crop density. No hardcoded counts. */
    private fun estimatePlantCount(plot: CropPlot): Int {
        val areaSqm = plot.widthM * plot.heightM
        return (areaSqm / 0.5f).toInt().coerceAtLeast(1)
    }
}

/**
 * Returns a live stream of all active crop plots for the farm canvas.
 * Drives isometric canvas rendering — plot positions, soil, crop come from Room.
 */
class GetFarmPlotsUseCase(
    private val plotRepository: CropPlotRepository
) {
    operator fun invoke(farmId: String): Flow<List<CropPlot>> =
        plotRepository.observePlots(farmId)
}

// ─── Edit Mode Use Cases ───────────────────────────────────────────────────

/**
 * Persists the full set of edited crop plots after SAVE CHANGES is tapped.
 */
class SaveFarmLayoutUseCase(
    private val plotRepository: CropPlotRepository,
    private val syncRepository: SyncRepository
) {
    suspend operator fun invoke(plots: List<CropPlot>) {
        plotRepository.savePlots(plots)
    }
}

/**
 * Soft-deletes a crop plot from the farm layout.
 */
class DeletePlotUseCase(
    private val plotRepository: CropPlotRepository
) {
    suspend operator fun invoke(plotId: String) =
        plotRepository.deletePlot(plotId)
}

/**
 * Inserts a new crop plot created in Edit Mode (Add Plot tool).
 */
class AddPlotUseCase(
    private val plotRepository: CropPlotRepository
) {
    suspend operator fun invoke(plot: CropPlot) =
        plotRepository.upsertPlot(plot)
}

// ─── Notification Use Cases ────────────────────────────────────────────────

class GetUnreadNotificationCountUseCase(
    private val notificationRepository: NotificationRepository
) {
    operator fun invoke(userId: String): Flow<Int> =
        notificationRepository.observeUnreadCount(userId)
}

class GetNotificationsUseCase(
    private val notificationRepository: NotificationRepository
) {
    operator fun invoke(userId: String): Flow<List<Notification>> =
        notificationRepository.observeAllNotifications(userId)
}

class MarkNotificationReadUseCase(
    private val notificationRepository: NotificationRepository
) {
    suspend operator fun invoke(notificationId: String) =
        notificationRepository.markRead(notificationId)
}

// ─── Calendar Use Cases ────────────────────────────────────────────────────

class GetAllTasksUseCase(
    private val taskRepository: TaskRepository
) {
    operator fun invoke(farmerId: String): Flow<List<FarmTask>> =
        taskRepository.observeAllTasks(farmerId)
}

class GetTasksForDateRangeUseCase(
    private val taskRepository: TaskRepository
) {
    operator fun invoke(farmerId: String, startDate: String, endDate: String): Flow<List<FarmTask>> =
        taskRepository.observeTasksForRange(farmerId, startDate, endDate)
}

class CompleteTaskUseCase(
    private val taskRepository: TaskRepository
) {
    suspend operator fun invoke(taskId: String, completedAt: String) =
        taskRepository.completeTask(taskId, completedAt)
}

// ─── Library Use Cases ─────────────────────────────────────────────────────

class GetAllCropsUseCase(
    private val cropRepository: CropRepository
) {
    operator fun invoke(): Flow<List<Crop>> =
        cropRepository.observeAllCrops()
}

class GetCropByNameUseCase(
    private val cropRepository: CropRepository
) {
    operator fun invoke(name: String): Flow<Crop?> =
        cropRepository.observeCropByName(name)
}

// ─── Farm Management Use Cases ─────────────────────────────────────────────

class GetFarmsUseCase(
    private val farmRepository: FarmRepository
) {
    operator fun invoke(farmerId: String): Flow<List<Farm>> =
        farmRepository.observeFarms(farmerId)
}

// ─── Harvest Use Cases ─────────────────────────────────────────────────────

class RecordHarvestUseCase(
    private val harvestRepository: HarvestRepository
) {
    suspend operator fun invoke(record: HarvestRecord) =
        harvestRepository.recordHarvest(record)
}
