package com.maptanim.app.domain.model

import com.maptanim.app.domain.model.SoilType

// ─── Farm ──────────────────────────────────────────────────────────────────

data class Farm(
    val id: String,
    val farmerId: String,
    val farmName: String,      // e.g. "Murcia Farm"
    val location: String,      // e.g. "Murcia, Negros Occidental"
    val totalAreaSqm: Float?,
    val createdAt: String,
    val updatedAt: String
)

// ─── CropPlot ─────────────────────────────────────────────────────────────

data class CropPlot(
    val id: String,
    val farmId: String,
    val plotLabel: String,      // "PLOT 1", "PLOT A", etc.
    val cropName: String?,      // null = no crop assigned
    val cropId: String?,
    val soilType: SoilType,     // loaded from crop_plots.soil_type via Room
    val posX: Float,            // meters from farm origin
    val posY: Float,
    val widthM: Float,
    val heightM: Float,
    val rotationDeg: Float,
    val plantedDate: String?,   // ISO-8601 date string, null if not planted
    val isActive: Boolean,
    val notes: String?,
    val createdAt: String,
    val updatedAt: String
)

// ─── Crop (reference data from crops table) ────────────────────────────────

data class Crop(
    val id: String,
    val name: String,                    // "Tomato"
    val localName: String?,             // "Kamatis"
    val botanicalName: String?,
    val category: String,               // DA/PSA 8-category classification
    val daysToHarvest: Int,
    val wateringIntervalDays: Int,
    val fertilizeIntervalDays: Int,
    val nRatio: Float,
    val pRatio: Float,
    val kRatio: Float,
    val optimalPhMin: Float,
    val optimalPhMax: Float,
    val idealSoils: List<SoilType>,
    val suitableSoils: List<SoilType>,
    val toleratedSoils: List<SoilType>,
    val pestRiskSeason: List<String>,   // ["WET", "DRY"]
    val seasonality: List<String>,      // ["DRY", "WET", "YEAR_ROUND"]
    val imageUrl: String?               // Supabase Storage public URL
)

// ─── FarmTask (generated by DSS, stored in tasks table) ───────────────────

data class FarmTask(
    val id: String,
    val farmId: String,
    val plotId: String,
    val plotLabel: String,      // denormalized from crop_plots.plot_label
    val cropName: String?,      // denormalized from crop_plots.crop_name
    val taskType: TaskType,
    val title: String,          // "Water Plot 3"
    val subLabel: String?,      // "Tomato"
    val dueDate: String,        // ISO-8601 date
    val isCompleted: Boolean,
    val completedAt: String?
)

// ─── FarmSummary (derived from plots + tasks via UseCases) ────────────────

data class FarmSummary(
    val totalPlots: Int = 0,
    val totalPlants: Int = 0,
    val readyToHarvest: Int = 0,
    val activeAlerts: Int = 0
)

// ─── HarvestRecord ─────────────────────────────────────────────────────────

data class HarvestRecord(
    val id: String,
    val plotId: String,
    val farmId: String,
    val cropName: String,
    val yieldKg: Float,
    val qualityRating: Int,   // 1–5
    val harvestedAt: String,
    val notes: String?
)

// ─── Activity (farmer manual log) ─────────────────────────────────────────

data class Activity(
    val id: String,
    val plotId: String,
    val farmId: String,
    val type: TaskType,
    val notes: String?,
    val performedAt: String
)

// ─── Notification ──────────────────────────────────────────────────────────

data class Notification(
    val id: String,
    val userId: String,
    val title: String,
    val body: String?,
    val taskType: TaskType?,
    val isRead: Boolean,
    val createdAt: String
)

// ─── Profile ──────────────────────────────────────────────────────────────

data class Profile(
    val id: String,             // equals auth.uid()
    val email: String,
    val nickname: String,
    val avatarUrl: String?,     // Supabase Storage user-avatars/{userId}/avatar.jpg
    val role: UserRole,
    val onboardingCompleted: Boolean,
    val createdAt: String
)

// ─── CropZone (sub-region of a CropPlot) ──────────────────────────────────

data class CropZone(
    val id: String,
    val plotId: String,
    val cropName: String?,          // null = empty zone (shows + placeholder)
    val cropId: String?,
    val offsetX: Float,             // meters from plot origin (top-left)
    val offsetY: Float,
    val widthM: Float,              // zone width in meters
    val heightM: Float,             // zone height in meters
    val spacingM: Float = 0.3f,     // plant-to-plant spacing in meters
    val createdAt: String = "",
    val updatedAt: String = ""
)

// ─── PlantInstance (computed at runtime, not persisted) ───────────────────

data class PlantInstance(
    val worldX: Float,              // absolute world position in meters
    val worldY: Float,
    val scaleFactor: Float,         // proportional to zone area
    val cropName: String
)

// ─── FarmObject (trellis, fence, exterior tree, decoration) ───────────────

data class FarmObject(
    val id: String,
    val farmId: String,
    val objectType: FarmObjectType,
    val worldX: Float,
    val worldY: Float,
    val widthM: Float,
    val heightM: Float,
    val rotationDeg: Float = 0f,
    val attachedPlotId: String? = null,
    val createdAt: String = "",
    val updatedAt: String = ""
)
