import { Farmer, Farm, BedPlot, CropZone, Crop, DSSRule, FeedbackItem, SystemAuditLog, DashboardStats, UserActivityLog, UserTrackingMetrics } from '../types';

export const MOCK_FARMERS: Farmer[] = [
    {
        id: 'usr-001',
        email: 'jomarey.parreno@gmail.com',
        fullName: 'Jomarey D. Parreño',
        phoneNumber: '+63 917 123 4567',
        role: 'FARMER',
        status: 'ACTIVE',
        farmName: 'Highland Organic Farm',
        activePlotsCount: 14,
        createdAt: '2026-01-15T08:30:00Z',
        lastLoginAt: '2026-09-05T21:15:00Z',
        lastActiveAt: '10 minutes ago',
        daysInactive: 0,
        deviceInfo: 'Android 14 (MapTanim v1.2.4)',
        isOnline: true,
        activitySummary: 'Updated Plot A1 crop stage & logged soil moisture test',
    },
    {
        id: 'usr-002',
        email: 'ryan.vasquez@gmail.com',
        fullName: 'John Ryan R. Vasquez',
        phoneNumber: '+63 918 987 6543',
        role: 'FARMER',
        status: 'ACTIVE',
        farmName: 'Vasquez Highland Crops',
        activePlotsCount: 22,
        createdAt: '2026-02-01T09:12:00Z',
        lastLoginAt: '2026-09-05T18:45:00Z',
        lastActiveAt: '4 hours ago',
        daysInactive: 0,
        deviceInfo: 'Android 13 (MapTanim v1.2.4)',
        isOnline: false,
        activitySummary: 'Queried DSS companion rule for Cabbage and Tomato',
    },
    {
        id: 'usr-003',
        email: 'jason.juanillo@gmail.com',
        fullName: 'Jason B. Juanillo',
        phoneNumber: '+63 920 333 7777',
        role: 'FARMER',
        status: 'ACTIVE',
        farmName: 'Green Valley Plot',
        activePlotsCount: 18,
        createdAt: '2026-03-10T14:20:00Z',
        lastLoginAt: '2026-09-04T07:05:00Z',
        lastActiveAt: '1 day ago',
        daysInactive: 1,
        deviceInfo: 'Android 12 (MapTanim v1.2.2)',
        isOnline: false,
        activitySummary: 'Recorded harvest yield (180kg Eggplant)',
    },
    {
        id: 'usr-004',
        email: 'maria.santos@gmail.com',
        fullName: 'Maria Santos',
        phoneNumber: '+63 928 444 8888',
        role: 'FARMER',
        status: 'INACTIVE',
        farmName: 'Santos Family Garden',
        activePlotsCount: 8,
        createdAt: '2026-04-12T11:00:00Z',
        lastLoginAt: '2026-08-11T09:20:00Z',
        lastActiveAt: '25 days ago',
        daysInactive: 25,
        deviceInfo: 'Android 11 (MapTanim v1.1.0)',
        isOnline: false,
        activitySummary: 'No field synchronization recorded in 25 days',
    },
    {
        id: 'usr-005',
        email: 'pedro.reyes@gmail.com',
        fullName: 'Pedro Reyes',
        phoneNumber: '+63 919 555 9999',
        role: 'FARMER',
        status: 'SUSPENDED',
        farmName: 'Reyes Eco Farm',
        activePlotsCount: 0,
        createdAt: '2026-04-05T13:40:00Z',
        lastLoginAt: '2026-06-12T09:30:00Z',
        lastActiveAt: '85 days ago',
        daysInactive: 85,
        deviceInfo: 'Android 10',
        isOnline: false,
        activitySummary: 'Account suspended due to policy violation in seed swap forum',
    },
    {
        id: 'usr-006',
        email: 'alicia.gonzales@gmail.com',
        fullName: 'Alicia B. Gonzales',
        phoneNumber: '+63 922 888 1234',
        role: 'FARMER',
        status: 'ACTIVE',
        farmName: 'Gonzales Hydro Farm',
        activePlotsCount: 16,
        createdAt: '2026-05-18T10:00:00Z',
        lastLoginAt: '2026-09-05T14:30:00Z',
        lastActiveAt: '8 hours ago',
        daysInactive: 0,
        deviceInfo: 'Android 14 (MapTanim v1.2.4)',
        isOnline: false,
        activitySummary: 'Completed weekly irrigation task for Pechay beds',
    },
    {
        id: 'usr-008',
        email: 'tomas.dela_cruz@yahoo.com',
        fullName: 'Tomas Dela Cruz',
        phoneNumber: '+63 930 111 2233',
        role: 'FARMER',
        status: 'INACTIVE',
        farmName: 'Dela Cruz Lowland Farm',
        activePlotsCount: 5,
        createdAt: '2026-03-22T08:45:00Z',
        lastLoginAt: '2026-08-18T16:10:00Z',
        lastActiveAt: '18 days ago',
        daysInactive: 18,
        deviceInfo: 'Android 12 (MapTanim v1.1.8)',
        isOnline: false,
        activitySummary: 'Dormant: No plot updates or tasks logged since harvest',
    },
    {
        id: 'usr-009',
        email: 'carolina.morales@gmail.com',
        fullName: 'Carolina Morales',
        phoneNumber: '+63 945 777 9988',
        role: 'FARMER',
        status: 'PENDING',
        farmName: 'Morales Backyard Patch',
        activePlotsCount: 3,
        createdAt: '2026-09-04T15:20:00Z',
        lastLoginAt: '2026-09-04T15:25:00Z',
        lastActiveAt: '1 day ago',
        daysInactive: 1,
        deviceInfo: 'Android 13 (MapTanim v1.2.4)',
        isOnline: false,
        activitySummary: 'New registrant awaiting agricultural extension validation',
    },
];

export const MOCK_USER_ACTIVITY_LOGS: UserActivityLog[] = [
    {
        id: 'act-001',
        userId: 'usr-001',
        userName: 'Jomarey D. Parreño',
        action: 'CROP_ZONE_UPDATE',
        module: 'Farm Operations',
        timestamp: '10 minutes ago',
        details: 'Transitioned Plot A1 (Carrots) to Growth Stage 3 (Vegetative)',
        status: 'ONLINE',
    },
    {
        id: 'act-002',
        userId: 'usr-007',
        userName: 'Engr. Eduardo Mendoza',
        action: 'BROADCAST_ADVISORY',
        module: 'DSS & Extension',
        timestamp: '1 hour ago',
        details: 'Issued Fall Armyworm alert to 48 corn farmers in Murcia sector',
        status: 'ONLINE',
    },
    {
        id: 'act-003',
        userId: 'usr-002',
        userName: 'John Ryan R. Vasquez',
        action: 'DSS_RULE_QUERY',
        module: 'Companion Matrix',
        timestamp: '4 hours ago',
        details: 'Consulted companion pairing for Cabbage and Tomato in Highland zone',
        status: 'ACTIVE',
    },
    {
        id: 'act-004',
        userId: 'usr-006',
        userName: 'Alicia B. Gonzales',
        action: 'TASK_COMPLETED',
        module: 'Field Tasks',
        timestamp: '8 hours ago',
        details: 'Marked weekly organic fertilizer application completed for 6 plots',
        status: 'ACTIVE',
    },
    {
        id: 'act-005',
        userId: 'usr-003',
        userName: 'Jason B. Juanillo',
        action: 'HARVEST_LOG',
        module: 'Yield Management',
        timestamp: '1 day ago',
        details: 'Logged 180kg Eggplant harvest (Grade A) from Green Valley Plot',
        status: 'ACTIVE',
    },
    {
        id: 'act-006',
        userId: 'usr-008',
        userName: 'Tomas Dela Cruz',
        action: 'INACTIVE_WARNING',
        module: 'Activity Tracker',
        timestamp: '18 days ago',
        details: 'Marked dormant: No synchronizations recorded past 14-day threshold',
        status: 'INACTIVE',
    },
    {
        id: 'act-007',
        userId: 'usr-004',
        userName: 'Maria Santos',
        action: 'INACTIVE_WARNING',
        module: 'Activity Tracker',
        timestamp: '25 days ago',
        details: 'Marked dormant: Offline since August 11, plot monitoring stalled',
        status: 'INACTIVE',
    },
];

export const MOCK_USER_TRACKING_METRICS: UserTrackingMetrics = {
    totalUsers: 148,
    activeUsers: 116,
    inactiveUsers: 22,
    suspendedUsers: 4,
    pendingUsers: 6,
    activeRate: 78.4,
    dailyActiveUsers: 68,
    weeklyActiveUsers: 116,
    statusDistribution: [
        { name: 'Active (Engaged)', value: 116, color: '#4CAF50', count: 116 },
        { name: 'Inactive / Dormant', value: 22, color: '#F4A261', count: 22 },
        { name: 'Pending Approval', value: 6, color: '#00BCD4', count: 6 },
        { name: 'Suspended', value: 4, color: '#E76F51', count: 4 },
    ],
    activityTrends: [
        { period: 'Mon', active: 98, inactive: 32, newRegistrations: 4 },
        { period: 'Tue', active: 104, inactive: 28, newRegistrations: 7 },
        { period: 'Wed', active: 108, inactive: 26, newRegistrations: 5 },
        { period: 'Thu', active: 112, inactive: 24, newRegistrations: 9 },
        { period: 'Fri', active: 119, inactive: 21, newRegistrations: 12 },
        { period: 'Sat', active: 114, inactive: 23, newRegistrations: 8 },
        { period: 'Sun', active: 116, inactive: 22, newRegistrations: 6 },
    ],
    activityByModule: [
        { module: 'Farm Plots & Soil Grid', count: 480, color: '#4CAF50' },
        { module: 'DSS Companion Rules', count: 345, color: '#00BCD4' },
        { module: 'Yield & Harvest Logs', count: 260, color: '#6FAF5A' },
        { module: 'Pest Advisory & Alerts', count: 195, color: '#F4A261' },
        { module: 'Community Exchange', count: 140, color: '#4C579E' },
    ],
};



export const MOCK_CROPS: Crop[] = [
    {
        id: 'crop-001',
        name: 'String Beans (Sitaw)',
        botanicalName: 'Vigna unguiculata (Sandigan F1)',
        category: 'PODDED',
        idealSoil: 'LOAM',
        season: 'YEAR_ROUND',
        daysToHarvest: 48,
        waterReqMmPerWeek: 40,
        npkRequirement: { nitrogen: 30, phosphorus: 60, potassium: 60 },
        companionCropsGood: ['Corn', 'Cucumber', 'Eggplant'],
        companionCropsBad: ['Onion', 'Garlic'],
        imageUrl: '/metadata/crops_images/sitaw.png',
        activePlantingCount: 38,
    },
    {
        id: 'crop-002',
        name: 'Eggplant (Talong)',
        botanicalName: 'Solanum melongena (Morena F1)',
        category: 'FRUIT',
        idealSoil: 'LOAM',
        season: 'YEAR_ROUND',
        daysToHarvest: 75,
        waterReqMmPerWeek: 45,
        npkRequirement: { nitrogen: 100, phosphorus: 80, potassium: 120 },
        companionCropsGood: ['String Beans', 'Spinach', 'Pepper'],
        companionCropsBad: ['Fennel'],
        imageUrl: '/metadata/crops_images/eggplant.png',
        activePlantingCount: 56,
    },
    {
        id: 'crop-003',
        name: 'Tomato (Kamatis)',
        botanicalName: 'Solanum lycopersicum (Diamante Max F1)',
        category: 'FRUIT',
        idealSoil: 'LOAM',
        season: 'YEAR_ROUND',
        daysToHarvest: 60,
        waterReqMmPerWeek: 50,
        npkRequirement: { nitrogen: 120, phosphorus: 100, potassium: 180 },
        companionCropsGood: ['Carrot', 'Onion', 'Basil'],
        companionCropsBad: ['Potato', 'Cabbage'],
        imageUrl: '/metadata/crops_images/tomato.png',
        activePlantingCount: 65,
    },
    {
        id: 'crop-004',
        name: 'Carrot (Karots)',
        botanicalName: 'Daucus carota (Terracotta F1)',
        category: 'ROOT',
        idealSoil: 'LOAM',
        season: 'DRY',
        daysToHarvest: 85,
        waterReqMmPerWeek: 35,
        npkRequirement: { nitrogen: 75, phosphorus: 120, potassium: 150 },
        companionCropsGood: ['Lettuce', 'Onion', 'Tomato'],
        companionCropsBad: ['Fennel', 'Dill'],
        imageUrl: '/metadata/crops_images/carrot.png',
        activePlantingCount: 42,
    },
    {
        id: 'crop-005',
        name: 'Red Onion (Sibuyas)',
        botanicalName: 'Allium cepa (Red Pinoy F1)',
        category: 'ROOT',
        idealSoil: 'LOAM',
        season: 'DRY',
        daysToHarvest: 110,
        waterReqMmPerWeek: 30,
        npkRequirement: { nitrogen: 90, phosphorus: 110, potassium: 130 },
        companionCropsGood: ['Tomato', 'Carrot', 'Pechay'],
        companionCropsBad: ['String Beans', 'Peas'],
        imageUrl: '/metadata/crops_images/onion.png',
        activePlantingCount: 34,
    },
    {
        id: 'crop-006',
        name: 'Squash / Pumpkin (Kalabasa)',
        botanicalName: 'Cucurbita moschata (Suprema F1)',
        category: 'FRUIT',
        idealSoil: 'LOAM',
        season: 'YEAR_ROUND',
        daysToHarvest: 80,
        waterReqMmPerWeek: 45,
        npkRequirement: { nitrogen: 80, phosphorus: 90, potassium: 140 },
        companionCropsGood: ['Corn', 'Beans', 'Radish'],
        companionCropsBad: ['Potato'],
        imageUrl: '/metadata/crops_images/pumpkin.png',
        activePlantingCount: 27,
    },
    {
        id: 'crop-007',
        name: 'Sweet Corn (Mais)',
        botanicalName: 'Zea mays (Machismo F1)',
        category: 'FRUIT',
        idealSoil: 'LOAM',
        season: 'YEAR_ROUND',
        daysToHarvest: 65,
        waterReqMmPerWeek: 55,
        npkRequirement: { nitrogen: 140, phosphorus: 80, potassium: 100 },
        companionCropsGood: ['String Beans', 'Squash', 'Cucumber'],
        companionCropsBad: ['Tomato'],
        imageUrl: '/metadata/crops_images/corn.png',
        activePlantingCount: 45,
    },
    {
        id: 'crop-008',
        name: 'Cabbage (Repolyo)',
        botanicalName: 'Brassica oleracea (K-S Cross F1)',
        category: 'LEAFY',
        idealSoil: 'CLAY',
        season: 'DRY',
        daysToHarvest: 60,
        waterReqMmPerWeek: 40,
        npkRequirement: { nitrogen: 150, phosphorus: 90, potassium: 120 },
        companionCropsGood: ['Onion', 'Potato', 'Celery'],
        companionCropsBad: ['Tomato', 'Strawberry'],
        imageUrl: '/metadata/crops_images/cabbage.png',
        activePlantingCount: 29,
    },
    {
        id: 'crop-009',
        name: 'Pechay (Pechay)',
        botanicalName: 'Brassica rapa (Pavon)',
        category: 'LEAFY',
        idealSoil: 'LOAM',
        season: 'YEAR_ROUND',
        daysToHarvest: 28,
        waterReqMmPerWeek: 35,
        npkRequirement: { nitrogen: 110, phosphorus: 60, potassium: 80 },
        companionCropsGood: ['Onion', 'Carrot', 'Cucumber'],
        companionCropsBad: ['Strawberry'],
        imageUrl: '/metadata/crops_images/pechay.png',
        activePlantingCount: 51,
    },
    {
        id: 'crop-010',
        name: 'Bitter Gourd (Ampalaya)',
        botanicalName: 'Momordica charantia (Jade Star XL F1)',
        category: 'FRUIT',
        idealSoil: 'LOAM',
        season: 'YEAR_ROUND',
        daysToHarvest: 55,
        waterReqMmPerWeek: 45,
        npkRequirement: { nitrogen: 90, phosphorus: 70, potassium: 100 },
        companionCropsGood: ['String Beans', 'Corn'],
        companionCropsBad: ['Potato'],
        imageUrl: '/metadata/crops_images/ampalaya.png',
        activePlantingCount: 31,
    },
    {
        id: 'crop-011',
        name: 'Okra (Okra)',
        botanicalName: 'Abelmoschus esculentus (Smooth Green)',
        category: 'PODDED',
        idealSoil: 'LOAM',
        season: 'YEAR_ROUND',
        daysToHarvest: 45,
        waterReqMmPerWeek: 40,
        npkRequirement: { nitrogen: 80, phosphorus: 60, potassium: 90 },
        companionCropsGood: ['Eggplant', 'Pepper', 'Cucumber'],
        companionCropsBad: ['Squash'],
        imageUrl: '/metadata/crops_images/okra.png',
        activePlantingCount: 36,
    },
    {
        id: 'crop-012',
        name: 'Chili Pepper (Sili)',
        botanicalName: 'Capsicum annuum (Django F1 Siling Haba)',
        category: 'FRUIT',
        idealSoil: 'LOAM',
        season: 'YEAR_ROUND',
        daysToHarvest: 65,
        waterReqMmPerWeek: 40,
        npkRequirement: { nitrogen: 110, phosphorus: 85, potassium: 130 },
        companionCropsGood: ['Eggplant', 'Tomato', 'Basil'],
        companionCropsBad: ['Fennel'],
        imageUrl: '/metadata/crops_images/sili.png',
        activePlantingCount: 48,
    },
    {
        id: 'crop-013',
        name: 'Cucumber (Pipino)',
        botanicalName: 'Cucumis sativus (Green Globe F1)',
        category: 'FRUIT',
        idealSoil: 'LOAM',
        season: 'YEAR_ROUND',
        daysToHarvest: 60,
        waterReqMmPerWeek: 50,
        npkRequirement: { nitrogen: 100, phosphorus: 70, potassium: 140 },
        companionCropsGood: ['Corn', 'String Beans', 'Okra'],
        companionCropsBad: ['Potato'],
        imageUrl: '/metadata/crops_images/pipino.png',
        activePlantingCount: 22,
    },
    {
        id: 'crop-014',
        name: 'Lettuce (Litsugas)',
        botanicalName: 'Lactuca sativa (General F1)',
        category: 'LEAFY',
        idealSoil: 'LOAM',
        season: 'WET',
        daysToHarvest: 45,
        waterReqMmPerWeek: 30,
        npkRequirement: { nitrogen: 120, phosphorus: 50, potassium: 80 },
        companionCropsGood: ['Carrot', 'Tomato', 'Onion'],
        companionCropsBad: ['Celery'],
        imageUrl: '/metadata/crops_images/lettuce.png',
        activePlantingCount: 19,
    },
    {
        id: 'crop-015',
        name: 'Water Spinach (Kangkong)',
        botanicalName: 'Ipomoea aquatica (Tsina)',
        category: 'LEAFY',
        idealSoil: 'LOAM',
        season: 'YEAR_ROUND',
        daysToHarvest: 30,
        waterReqMmPerWeek: 50,
        npkRequirement: { nitrogen: 110, phosphorus: 50, potassium: 70 },
        companionCropsGood: ['Pechay', 'Cucumber', 'Eggplant'],
        companionCropsBad: [],
        imageUrl: '/metadata/crops_images/kangkong.png',
        activePlantingCount: 35,
    },
];

export const MOCK_PESTS = [
    {
        id: 'pest-001',
        name: 'Fruit Borer / Corn Earworm',
        localName: 'Ubod ng Kamatis / Harabas',
        scientificName: 'Helicoverpa armigera',
        affectedCrops: ['Tomato', 'Eggplant', 'Corn', 'Okra', 'Chili Pepper'],
        category: 'Insect Pest',
        organicControl: 'Spray Neem Oil extract (30ml/L water) or Bacillus thuringiensis (Bt). Handpick caterpillars early morning.',
        chemicalControl: 'Apply DA-approved Chlorantraniliprole or Emamectin benzoate at early instar stage.',
        preventionTips: 'Practice crop rotation with non-host crops. Install yellow sticky traps.',
        imageUrl: '/metadata/pest/Fruit_borer.png'
    },
    {
        id: 'pest-002',
        name: 'Tomato Leaf Curl Virus (TyLCV)',
        localName: 'Kulot sa Kamatis / Whitefly Disease',
        scientificName: 'Begomovirus (transmitted by Bemisia tabaci)',
        affectedCrops: ['Tomato', 'Chili Pepper', 'Squash'],
        category: 'Viral Disease',
        organicControl: 'Spray soapy water or Neem oil to target whitefly vector. Remove infected plants immediately.',
        chemicalControl: 'Control vector whiteflies with Imidacloprid or Thiamethoxam during seedling stage.',
        preventionTips: 'Use TyLCV-resistant varieties (e.g. Diamante Max F1). Install insect netting.',
        imageUrl: '/metadata/pest/Tomato_leaf_curlvirus.png'
    },
    {
        id: 'pest-003',
        name: 'Diamondback Moth',
        localName: 'Ulod sa Repolyo',
        scientificName: 'Plutella xylostella',
        affectedCrops: ['Cabbage', 'Pechay', 'Lettuce'],
        category: 'Insect Pest',
        organicControl: 'Apply Bt (Bacillus thuringiensis) kurstaki strain every 5-7 days.',
        chemicalControl: 'Rotate Spinetoram foliar sprays to prevent pesticide resistance.',
        preventionTips: 'Use overhead sprinkler irrigation to disturb egg-laying adult moths.',
        imageUrl: '/metadata/pest/Diamondback_moth.png'
    },
    {
        id: 'pest-004',
        name: 'Onion Thrips',
        localName: 'Peste sa Sibuyas / Thrips',
        scientificName: 'Thrips tabaci',
        affectedCrops: ['Onion', 'Carrot', 'Cabbage'],
        category: 'Insect Pest',
        organicControl: 'Blue sticky card traps (20 traps/ha). Spray bio-pesticide Beauveria bassiana.',
        chemicalControl: 'Apply Abamectin or Fipronil in severe infestations during bulb establishment.',
        preventionTips: 'Maintain proper soil moisture. Avoid planting near older onion fields.',
        imageUrl: '/metadata/pest/Onion_thrips.png'
    },
    {
        id: 'pest-005',
        name: 'Fall Armyworm',
        localName: 'Armyworm / Harabas sa Mais',
        scientificName: 'Spodoptera frugiperda',
        affectedCrops: ['Corn', 'String Beans', 'Cucumber'],
        category: 'Insect Pest',
        organicControl: 'Drop sand/ash mixed with Neem powder into corn whorls.',
        chemicalControl: 'Target whorls with Spinetoram or Methomyl sprays during early egg hatch.',
        preventionTips: 'Deep plowing after harvest to destroy pupae in soil.',
        imageUrl: '/metadata/pest/Fall_armyworm.png'
    },
    {
        id: 'pest-006',
        name: 'Powdery Mildew',
        localName: 'Pulbos sa Dahon ng Kalabasa',
        scientificName: 'Erysiphe cichoracearum',
        affectedCrops: ['Squash', 'Cucumber', 'Okra', 'Ampalaya'],
        category: 'Fungal Disease',
        organicControl: 'Foliar spray of 10% baking soda solution or diluted milk spray.',
        chemicalControl: 'Apply Potassium bicarbonate or Sulfur-based fungicide.',
        preventionTips: 'Ensure wider plant spacing for air circulation. Avoid overhead watering.',
        imageUrl: '/metadata/pest/Powdery_mildew.png'
    }
];

export const MOCK_SOILS = [
    {
        soilType: 'LOAM',
        title: 'Loam Soil',
        localName: 'Lupang Luto / Ideal Loam',
        description: 'Dark, rich, crumbly soil with a balanced mixture of sand, silt, and clay.',
        characteristics: 'Excellent moisture retention with optimal internal drainage; rich in humus.',
        drainageSpeed: 'Moderate / Ideal (15–25 mm/hr)',
        phRange: '6.0 – 7.0',
        texture: 'Crumbly and soft when dry, forms a loose ball when moist.',
        bestCrops: ['Tomato', 'Eggplant', 'Chili Pepper', 'Carrot', 'Onion', 'Lettuce', 'Corn', 'Squash'],
        imageUrl: '/metadata/soil_images/Loam_soil.png',
        colorHex: '#3E2723'
    },
    {
        soilType: 'CLAY',
        title: 'Clay Soil',
        localName: 'Lupang Malagkit / Pula',
        description: 'Fine-textured soil composed of dense clay mineral particles.',
        characteristics: 'Holds abundant plant nutrients; high water capacity; slow to drain.',
        drainageSpeed: 'Slow (< 5 mm/hr)',
        phRange: '5.5 – 7.0',
        texture: 'Sticky and smooth when wet, forms hard clods when dry.',
        bestCrops: ['Eggplant', 'Okra', 'Kangkong', 'Squash', 'Corn'],
        imageUrl: '/metadata/soil_images/Clay_soil.png',
        colorHex: '#5D4037'
    },
    {
        soilType: 'SANDY',
        title: 'Sandy Soil',
        localName: 'Lupang Buhangin',
        description: 'Coarse-grained soil with large quartz particles. Highly porous and fast-draining.',
        characteristics: 'Warms up rapidly in dry season; excellent root penetration.',
        drainageSpeed: 'Fast (> 50 mm/hr)',
        phRange: '5.5 – 6.8',
        texture: 'Gritty and loose, cannot hold form when squeezed.',
        bestCrops: ['Carrot', 'Chili Pepper', 'Onion', 'Tomato', 'Eggplant'],
        imageUrl: '/metadata/soil_images/Sandy_soil.png',
        colorHex: '#C6A700'
    },
    {
        soilType: 'SILTY',
        title: 'Silty Soil',
        localName: 'Lupang Banlik / River Silt',
        description: 'Smooth, fertile soil deposited by alluvial river beds.',
        characteristics: 'Very smooth texture; easily tilled; retains moisture efficiently.',
        drainageSpeed: 'Moderate (10–20 mm/hr)',
        phRange: '6.0 – 7.0',
        texture: 'Floury and smooth when dry, silky when moist.',
        bestCrops: ['Cabbage', 'Kangkong', 'Lettuce', 'String Beans', 'Pechay'],
        imageUrl: '/metadata/soil_images/Silty_soil.png',
        colorHex: '#795548'
    },
    {
        soilType: 'PEATY',
        title: 'Peaty Soil',
        localName: 'Lupang Organiko / Peat',
        description: 'Dark, spongy soil high in decomposed organic plant materials.',
        characteristics: 'High organic content; rich in nitrogen; naturally acidic.',
        drainageSpeed: 'Moderate to Slow',
        phRange: '4.5 – 6.0',
        texture: 'Spongy, dark brown or black, lightweight.',
        bestCrops: ['Lettuce', 'Cabbage', 'Kangkong', 'Pechay'],
        imageUrl: '/metadata/soil_images/Peaty_soil.png',
        colorHex: '#212121'
    },
    {
        soilType: 'CHALKY',
        title: 'Chalky Soil',
        localName: 'Lupang Apog / Alkaline',
        description: 'Light soil sitting over limestone bedrock. Rich in calcium carbonate.',
        characteristics: 'Alkaline pH; fast draining; benefits from regular organic matter.',
        drainageSpeed: 'Fast to Moderate',
        phRange: '7.0 – 8.0',
        texture: 'Stony or chalky white flecks throughout dry soil.',
        bestCrops: ['Okra', 'Corn', 'String Beans'],
        imageUrl: '/metadata/soil_images/Chalky_soil.png',
        colorHex: '#9E9E9E'
    }
];

export const MOCK_DSS_RULES: DSSRule[] = [
    {
        id: 'dss-001',
        cropA: 'Carrot (Karot)',
        cropB: 'Tomato (Kamatis)',
        relationship: 'BENEFICIAL',
        reason: 'Tomatoes produce solanine which deters carrot rust flies; carrots loosen soil for deep tomato root growth.',
        daReferenceDoc: 'MapTanim Companion Field Survey Vol 1',
    },
    {
        id: 'dss-002',
        cropA: 'Tomato (Kamatis)',
        cropB: 'Cabbage (Repolyo)',
        relationship: 'ANTAGONIST',
        reason: 'Both heavy nitrogen feeders competing for soil nutrients; high vulnerability to flea beetles.',
        daReferenceDoc: 'Agronomic Companion Field Study Sec 3.2',
    },
    {
        id: 'dss-003',
        cropA: 'String Beans (Sitao)',
        cropB: 'Eggplant (Talong)',
        relationship: 'BENEFICIAL',
        reason: 'Legumes fix atmospheric nitrogen directly benefiting nitrogen-hungry eggplants.',
        daReferenceDoc: 'Field Crop Rotation Survey 2025',
    },
];

export const MOCK_FARMS: Farm[] = [
    {
        id: 'farm-001',
        farmerId: 'usr-001',
        farmerName: 'Jomarey D. Parreño',
        farmName: 'Murcia Organic Farm',
        soilType: 'LOAM',
        bedsCount: 14,
        createdAt: '2026-01-15T08:30:00Z',
    },
    {
        id: 'farm-002',
        farmerId: 'usr-002',
        farmerName: 'John Ryan R. Vasquez',
        farmName: 'Vasquez Highland Crops',
        soilType: 'LOAM',
        bedsCount: 22,
        createdAt: '2026-02-01T09:12:00Z',
    },
];



export const MOCK_BEDS: CropZone[] = [
    // Farm 001 - Murcia Organic Farm
    { id: 'zone-001', farmId: 'farm-001', cropZoneLabel: 'Plot A1 - Carrots', cropId: 'crop-001', cropName: 'Carrot (Karot)', x: 12, y: 12, width: 3, height: 3, growthStage: 3, plantedDate: '2026-06-01', expectedHarvestDate: '2026-08-15', healthScore: 94 },
    { id: 'zone-002', farmId: 'farm-001', cropZoneLabel: 'Plot A2 - Tomatoes', cropId: 'crop-004', cropName: 'Tomato (Kamatis)', x: 18, y: 12, width: 4, height: 3, growthStage: 2, plantedDate: '2026-06-15', expectedHarvestDate: '2026-09-02', healthScore: 88 },
    { id: 'zone-003', farmId: 'farm-001', cropZoneLabel: 'Plot B1 - Sitaw Beans', cropId: 'crop-002', cropName: 'String Beans (Sitaw)', x: 12, y: 18, width: 4, height: 4, growthStage: 4, plantedDate: '2026-05-20', expectedHarvestDate: '2026-07-30', healthScore: 98 },
    { id: 'zone-004', farmId: 'farm-001', cropZoneLabel: 'Plot B2 - Eggplant', cropId: 'crop-003', cropName: 'Eggplant (Talong)', x: 20, y: 18, width: 3, height: 3, growthStage: 1, plantedDate: '2026-07-10', expectedHarvestDate: '2026-10-08', healthScore: 90 },
    { id: 'zone-005', farmId: 'farm-001', cropZoneLabel: 'Plot C1 - Sweet Corn', cropId: 'crop-007', cropName: 'Sweet Corn (Mais)', x: 26, y: 12, width: 5, height: 4, growthStage: 3, plantedDate: '2026-06-05', expectedHarvestDate: '2026-08-20', healthScore: 95 },
    { id: 'zone-006', farmId: 'farm-001', cropZoneLabel: 'Plot C2 - Squash/Kalabasa', cropId: 'crop-006', cropName: 'Squash (Kalabasa)', x: 26, y: 20, width: 5, height: 5, growthStage: 2, plantedDate: '2026-06-18', expectedHarvestDate: '2026-09-10', healthScore: 82 },
    { id: 'zone-007', farmId: 'farm-001', cropZoneLabel: 'Plot D1 - Chili Pepper', cropId: 'crop-012', cropName: 'Chili Pepper (Sili)', x: 12, y: 26, width: 3, height: 3, growthStage: 4, plantedDate: '2026-05-15', expectedHarvestDate: '2026-08-01', healthScore: 91 },
    { id: 'zone-008', farmId: 'farm-001', cropZoneLabel: 'Plot D2 - Pechay Bed', cropId: 'crop-009', cropName: 'Pechay (Pechay)', x: 18, y: 26, width: 3, height: 3, growthStage: 2, plantedDate: '2026-07-01', expectedHarvestDate: '2026-08-10', healthScore: 78 },

    // Farm 002 - Vasquez Highland Crops
    { id: 'zone-101', farmId: 'farm-002', cropZoneLabel: 'Highland Cabbage Plot', cropId: 'crop-008', cropName: 'Cabbage (Repolyo)', x: 15, y: 15, width: 4, height: 4, growthStage: 3, plantedDate: '2026-06-10', expectedHarvestDate: '2026-08-25', healthScore: 96 },
    { id: 'zone-102', farmId: 'farm-002', cropZoneLabel: 'Ampalaya Trellis Zone', cropId: 'crop-010', cropName: 'Bitter Gourd (Ampalaya)', x: 22, y: 15, width: 4, height: 4, growthStage: 3, plantedDate: '2026-06-08', expectedHarvestDate: '2026-08-18', healthScore: 89 },
    { id: 'zone-103', farmId: 'farm-002', cropZoneLabel: 'Pipino Cucumber Bed', cropId: 'crop-013', cropName: 'Cucumber (Pipino)', x: 15, y: 22, width: 4, height: 3, growthStage: 1, plantedDate: '2026-07-05', expectedHarvestDate: '2026-09-05', healthScore: 92 },
];

export const MOCK_FEEDBACK: FeedbackItem[] = [
    {
        id: 'fb-101',
        farmerId: 'usr-001',
        farmerName: 'Jomarey D. Parreño',
        category: 'AGRONOMIC_QUERY',
        subject: 'Leaf yellowing on String Beans Plot B1',
        message: 'Noticeable yellow spots appearing on lower leaves after heavy rainfall last Tuesday. Should I increase Potassium or check drainage?',
        status: 'IN_PROGRESS',
        createdAt: '2026-07-27T14:22:00Z',
    },
    {
        id: 'fb-102',
        farmerId: 'usr-002',
        farmerName: 'John Ryan R. Vasquez',
        category: 'FEATURE_REQUEST',
        subject: 'Request for Weather Radar integration in DSS',
        message: 'It would be great to get automated warnings when rainfall prediction exceeds 50mm in Don Salvador Benedicto.',
        status: 'PENDING',
        createdAt: '2026-07-28T09:10:00Z',
    },
    {
        id: 'fb-103',
        farmerId: 'usr-003',
        farmerName: 'Jason B. Juanillo',
        category: 'BUG',
        subject: 'Offline sync badge delay on Android app',
        message: 'Completed tasks took 1 minute to reflect green checkmark when reconnecting to mobile data.',
        status: 'RESOLVED',
        createdAt: '2026-07-25T11:45:00Z',
        resolvedAt: '2026-07-26T16:00:00Z',
    },
];

export const MOCK_LOGS: SystemAuditLog[] = [
    {
        id: 'log-501',
        timestamp: '2026-07-29T11:20:00Z',
        adminEmail: 'admin@system.local',
        action: 'UPDATE_CROP_RULE',
        targetModule: 'DSS Rule Engine',
        details: 'Modified NPK ratio for Daucus carota (Carrot) based on DA 2026 guidelines.',
        status: 'SUCCESS',
        ipAddress: '112.198.75.12',
    },
    {
        id: 'log-502',
        timestamp: '2026-07-29T09:14:00Z',
        adminEmail: 'admin@system.local',
        action: 'USER_ROLE_CHANGE',
        targetModule: 'Farmer Management',
        details: 'Validated account for John Ryan R. Vasquez (Highland Farm).',
        status: 'SUCCESS',
        ipAddress: '112.198.75.12',
    },
    {
        id: 'log-503',
        timestamp: '2026-07-28T18:05:00Z',
        adminEmail: 'sys.bot@maptanim.ph',
        action: 'BACKUP_SYNC',
        targetModule: 'Database Cloud',
        details: 'Automated Supabase PostgreSQL snapshot completed (34 tables, 14MB).',
        status: 'SUCCESS',
        ipAddress: '10.0.4.18',
    },
];

export const MOCK_STATS: DashboardStats = {
    totalFarmers: 148,
    activeFarms: 132,
    totalPlots: 864,
    totalHarvestKgThisMonth: 3420,
    systemHealth: '99.98% Operational',
    monthlyYield: [
        { month: 'Jan', yieldKg: 2100, targetKg: 2000 },
        { month: 'Feb', yieldKg: 2450, targetKg: 2200 },
        { month: 'Mar', yieldKg: 2800, targetKg: 2500 },
        { month: 'Apr', yieldKg: 3100, targetKg: 2800 },
        { month: 'May', yieldKg: 2950, targetKg: 3000 },
        { month: 'Jun', yieldKg: 3300, targetKg: 3100 },
        { month: 'Jul', yieldKg: 3420, targetKg: 3300 },
    ],
    cropDistribution: [
        { category: 'Fruit Vegetables (Tomato/Talong)', value: 35, color: '#4caf50' },
        { category: 'Root Crops (Carrot)', value: 25, color: '#f59e0b' },
        { category: 'Podded (String Beans)', value: 20, color: '#0284c7' },
        { category: 'Leafy (Cabbage/Petchay)', value: 20, color: '#8b5cf6' },
    ],
    farmerRegistrations: [
        { date: 'Mon', count: 4 },
        { date: 'Tue', count: 7 },
        { date: 'Wed', count: 5 },
        { date: 'Thu', count: 9 },
        { date: 'Fri', count: 12 },
        { date: 'Sat', count: 8 },
        { date: 'Sun', count: 6 },
    ],
    totalCrops: 15,
    totalFeedback: 0,
    totalPostReports: 0,
    pendingReports: 0,
    topPlantedCrops: [
        { cropName: 'Tomato', varietyName: 'Diamante Max', plantCount: 42, color: '#ef4444' },
        { cropName: 'Eggplant', varietyName: 'Dumaguete Long', plantCount: 38, color: '#8b5cf6' },
        { cropName: 'Cabbage', varietyName: 'Scorpio', plantCount: 29, color: '#22c55e' },
        { cropName: 'Pechay', varietyName: 'Black Behi', plantCount: 24, color: '#84cc16' },
        { cropName: 'Okra', varietyName: 'Smooth Green', plantCount: 19, color: '#f59e0b' },
        { cropName: 'String Beans', varietyName: 'Sandigan', plantCount: 16, color: '#06b6d4' },
        { cropName: 'Bitter Gourd', varietyName: 'Galaxy F1', plantCount: 13, color: '#10b981' },
    ],
    topPlantedVarieties: [
        { varietyName: 'Diamante Max', cropName: 'Tomato (Kamatis)', plantCount: 42, color: '#ef4444' },
        { varietyName: 'Dumaguete Long', cropName: 'Eggplant (Talong)', plantCount: 38, color: '#8b5cf6' },
        { varietyName: 'Scorpio', cropName: 'Cabbage (Repolyo)', plantCount: 29, color: '#22c55e' },
        { varietyName: 'Black Behi', cropName: 'Pechay', plantCount: 24, color: '#84cc16' },
        { varietyName: 'Smooth Green', cropName: 'Okra', plantCount: 19, color: '#f59e0b' },
        { varietyName: 'Sandigan', cropName: 'String Beans (Sitaw)', plantCount: 16, color: '#06b6d4' },
        { varietyName: 'Galaxy F1', cropName: 'Bitter Gourd (Ampalaya)', plantCount: 13, color: '#10b981' },
    ],
    harvestDateAnalytics: {
        peakHarvestDate: '2026-09-15',
        peakHarvestYieldKg: 480,
        peakHarvestPlotCount: 16,
        peakHarvestCrop: 'Bitter Gourd (Galaxy F1)',
        dateRecords: [
            { date: '2026-08-20', displayDate: 'Aug 20', fullDate: 'Aug 20, 2026', harvestCount: 8, yieldKg: 280, topCrop: 'String Beans' },
            { date: '2026-08-25', displayDate: 'Aug 25', fullDate: 'Aug 25, 2026', harvestCount: 11, yieldKg: 340, topCrop: 'Cabbage' },
            { date: '2026-09-01', displayDate: 'Sep 01', fullDate: 'Sep 01, 2026', harvestCount: 12, yieldKg: 390, topCrop: 'Sweet Corn' },
            { date: '2026-09-05', displayDate: 'Sep 05', fullDate: 'Sep 05, 2026', harvestCount: 9, yieldKg: 310, topCrop: 'Eggplant' },
            { date: '2026-09-10', displayDate: 'Sep 10', fullDate: 'Sep 10, 2026', harvestCount: 14, yieldKg: 420, topCrop: 'Tomato' },
            { date: '2026-09-15', displayDate: 'Sep 15', fullDate: 'Sep 15, 2026', harvestCount: 16, yieldKg: 480, topCrop: 'Bitter Gourd' },
            { date: '2026-09-20', displayDate: 'Sep 20', fullDate: 'Sep 20, 2026', harvestCount: 10, yieldKg: 360, topCrop: 'Pechay' },
        ],
    },
    weeklyRegistrations: [
        { day: 'Mon', newUsers: 4, returningUsers: 12 },
        { day: 'Tue', newUsers: 7, returningUsers: 18 },
        { day: 'Wed', newUsers: 5, returningUsers: 14 },
        { day: 'Thu', newUsers: 9, returningUsers: 21 },
        { day: 'Fri', newUsers: 12, returningUsers: 25 },
        { day: 'Sat', newUsers: 8, returningUsers: 16 },
        { day: 'Sun', newUsers: 6, returningUsers: 11 },
    ],
    activeUsersToday: 0,
    totalCommunityPosts: 0,
    systemNotificationsCount: 0,
};


