import { Farmer, Farm, BedPlot, CropZone, Crop, DSSRule, FeedbackItem, SystemAuditLog, DashboardStats } from '../types';

export const MOCK_FARMERS: Farmer[] = [
    {
        id: 'usr-001',
        email: 'jomarey.parreno@gmail.com',
        fullName: 'Jomarey D. Parreño',
        phoneNumber: '+63 917 123 4567',
        role: 'FARMER',
        status: 'ACTIVE',
        farmName: 'Murcia Organic Farm',
        activePlotsCount: 14,
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
        createdAt: '2026-01-15T08:30:00Z',
        lastLoginAt: '2026-07-29T10:15:00Z',
    },
    {
        id: 'usr-002',
        email: 'ryan.vasquez@gmail.com',
        fullName: 'John Ryan R. Vasquez',
        phoneNumber: '+63 918 987 6543',
        role: 'FARMER',
        status: 'ACTIVE',
        farmName: 'Vasquez Highland Crops',
        activePlotsCount: 22,
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
        createdAt: '2026-02-01T09:12:00Z',
        lastLoginAt: '2026-07-28T16:45:00Z',
    },
    {
        id: 'usr-003',
        email: 'jason.juanillo@gmail.com',
        fullName: 'Jason B. Juanillo',
        phoneNumber: '+63 920 333 7777',
        role: 'FARMER',
        status: 'ACTIVE',
        farmName: 'Green Valley Plot',
        activePlotsCount: 18,
        createdAt: '2026-03-10T14:20:00Z',
        lastLoginAt: '2026-07-29T07:05:00Z',
    },
    {
        id: 'usr-004',
        email: 'maria.santos@gmail.com',
        fullName: 'Maria Santos',
        phoneNumber: '+63 928 444 8888',
        role: 'FARMER',
        status: 'PENDING',
        farmName: 'Santos Family Garden',
        activePlotsCount: 8,
        createdAt: '2026-07-20T11:00:00Z',
        lastLoginAt: '2026-07-20T11:05:00Z',
    },
    {
        id: 'usr-005',
        email: 'pedro.reyes@gmail.com',
        fullName: 'Pedro Reyes',
        phoneNumber: '+63 919 555 9999',
        role: 'FARMER',
        status: 'SUSPENDED',
        farmName: 'Reyes Eco Farm',
        activePlotsCount: 0,
        createdAt: '2026-04-05T13:40:00Z',
        lastLoginAt: '2026-06-12T09:30:00Z',
    },
];



export const MOCK_CROPS: Crop[] = [
    {
        id: 'crop-001',
        name: 'String Beans (Sitaw)',
        botanicalName: 'Vigna unguiculata (Sandigan F1)',
        category: 'PODDED',
        idealSoil: 'LOAM',
        season: 'YEAR_ROUND',
        daysToHarvest: 48,
        waterReqMmPerWeek: 40,
        npkRequirement: { nitrogen: 30, phosphorus: 60, potassium: 60 },
        companionCropsGood: ['Corn', 'Cucumber', 'Eggplant'],
        companionCropsBad: ['Onion', 'Garlic'],
        imageUrl: 'https://images.unsplash.com/photo-1567375698348-5d9d5ae99de0?auto=format&fit=crop&w=600&q=80',
        activePlantingCount: 38,
    },
    {
        id: 'crop-002',
        name: 'Eggplant (Talong)',
        botanicalName: 'Solanum melongena (Morena F1)',
        category: 'FRUIT',
        idealSoil: 'LOAM',
        season: 'YEAR_ROUND',
        daysToHarvest: 75,
        waterReqMmPerWeek: 45,
        npkRequirement: { nitrogen: 100, phosphorus: 80, potassium: 120 },
        companionCropsGood: ['String Beans', 'Spinach', 'Pepper'],
        companionCropsBad: ['Fennel'],
        imageUrl: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80',
        activePlantingCount: 56,
    },
    {
        id: 'crop-003',
        name: 'Tomato (Kamatis)',
        botanicalName: 'Solanum lycopersicum (Diamante Max F1)',
        category: 'FRUIT',
        idealSoil: 'LOAM',
        season: 'YEAR_ROUND',
        daysToHarvest: 60,
        waterReqMmPerWeek: 50,
        npkRequirement: { nitrogen: 120, phosphorus: 100, potassium: 180 },
        companionCropsGood: ['Carrot', 'Onion', 'Basil'],
        companionCropsBad: ['Potato', 'Cabbage'],
        imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80',
        activePlantingCount: 65,
    },
    {
        id: 'crop-004',
        name: 'Carrot (Karots)',
        botanicalName: 'Daucus carota (Terracotta F1)',
        category: 'ROOT',
        idealSoil: 'LOAM',
        season: 'DRY',
        daysToHarvest: 85,
        waterReqMmPerWeek: 35,
        npkRequirement: { nitrogen: 75, phosphorus: 120, potassium: 150 },
        companionCropsGood: ['Lettuce', 'Onion', 'Tomato'],
        companionCropsBad: ['Fennel', 'Dill'],
        imageUrl: 'https://images.unsplash.com/photo-1598170845058-12ef4a457539?auto=format&fit=crop&w=600&q=80',
        activePlantingCount: 42,
    },
    {
        id: 'crop-005',
        name: 'Red Onion (Sibuyas)',
        botanicalName: 'Allium cepa (Red Pinoy F1)',
        category: 'ROOT',
        idealSoil: 'LOAM',
        season: 'DRY',
        daysToHarvest: 110,
        waterReqMmPerWeek: 30,
        npkRequirement: { nitrogen: 90, phosphorus: 110, potassium: 130 },
        companionCropsGood: ['Tomato', 'Carrot', 'Pechay'],
        companionCropsBad: ['String Beans', 'Peas'],
        imageUrl: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cf?auto=format&fit=crop&w=600&q=80',
        activePlantingCount: 34,
    },
    {
        id: 'crop-006',
        name: 'Squash / Pumpkin (Kalabasa)',
        botanicalName: 'Cucurbita moschata (Suprema F1)',
        category: 'FRUIT',
        idealSoil: 'LOAM',
        season: 'YEAR_ROUND',
        daysToHarvest: 80,
        waterReqMmPerWeek: 45,
        npkRequirement: { nitrogen: 80, phosphorus: 90, potassium: 140 },
        companionCropsGood: ['Corn', 'Beans', 'Radish'],
        companionCropsBad: ['Potato'],
        imageUrl: 'https://images.unsplash.com/photo-1570586437263-ab629fccc818?auto=format&fit=crop&w=600&q=80',
        activePlantingCount: 27,
    },
    {
        id: 'crop-007',
        name: 'Sweet Corn (Mais)',
        botanicalName: 'Zea mays (Machismo F1)',
        category: 'FRUIT',
        idealSoil: 'LOAM',
        season: 'YEAR_ROUND',
        daysToHarvest: 65,
        waterReqMmPerWeek: 55,
        npkRequirement: { nitrogen: 140, phosphorus: 80, potassium: 100 },
        companionCropsGood: ['String Beans', 'Squash', 'Cucumber'],
        companionCropsBad: ['Tomato'],
        imageUrl: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=600&q=80',
        activePlantingCount: 45,
    },
    {
        id: 'crop-008',
        name: 'Cabbage (Repolyo)',
        botanicalName: 'Brassica oleracea (K-S Cross F1)',
        category: 'LEAFY',
        idealSoil: 'CLAY',
        season: 'DRY',
        daysToHarvest: 60,
        waterReqMmPerWeek: 40,
        npkRequirement: { nitrogen: 150, phosphorus: 90, potassium: 120 },
        companionCropsGood: ['Onion', 'Potato', 'Celery'],
        companionCropsBad: ['Tomato', 'Strawberry'],
        imageUrl: 'https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?auto=format&fit=crop&w=600&q=80',
        activePlantingCount: 29,
    },
    {
        id: 'crop-009',
        name: 'Pechay (Pechay)',
        botanicalName: 'Brassica rapa (Pavon)',
        category: 'LEAFY',
        idealSoil: 'LOAM',
        season: 'YEAR_ROUND',
        daysToHarvest: 28,
        waterReqMmPerWeek: 35,
        npkRequirement: { nitrogen: 110, phosphorus: 60, potassium: 80 },
        companionCropsGood: ['Onion', 'Carrot', 'Cucumber'],
        companionCropsBad: ['Strawberry'],
        imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
        activePlantingCount: 51,
    },
    {
        id: 'crop-010',
        name: 'Bitter Gourd (Ampalaya)',
        botanicalName: 'Momordica charantia (Jade Star XL F1)',
        category: 'FRUIT',
        idealSoil: 'LOAM',
        season: 'YEAR_ROUND',
        daysToHarvest: 55,
        waterReqMmPerWeek: 45,
        npkRequirement: { nitrogen: 90, phosphorus: 70, potassium: 100 },
        companionCropsGood: ['String Beans', 'Corn'],
        companionCropsBad: ['Potato'],
        imageUrl: 'https://images.unsplash.com/photo-1588615419955-5233519894e6?auto=format&fit=crop&w=600&q=80',
        activePlantingCount: 31,
    },
    {
        id: 'crop-011',
        name: 'Okra (Okra)',
        botanicalName: 'Abelmoschus esculentus (Smooth Green)',
        category: 'PODDED',
        idealSoil: 'LOAM',
        season: 'YEAR_ROUND',
        daysToHarvest: 45,
        waterReqMmPerWeek: 40,
        npkRequirement: { nitrogen: 80, phosphorus: 60, potassium: 90 },
        companionCropsGood: ['Eggplant', 'Pepper', 'Cucumber'],
        companionCropsBad: ['Squash'],
        imageUrl: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=600&q=80',
        activePlantingCount: 36,
    },
    {
        id: 'crop-012',
        name: 'Chili Pepper (Sili)',
        botanicalName: 'Capsicum annuum (Django F1 Siling Haba)',
        category: 'FRUIT',
        idealSoil: 'LOAM',
        season: 'YEAR_ROUND',
        daysToHarvest: 65,
        waterReqMmPerWeek: 40,
        npkRequirement: { nitrogen: 110, phosphorus: 85, potassium: 130 },
        companionCropsGood: ['Eggplant', 'Tomato', 'Basil'],
        companionCropsBad: ['Fennel'],
        imageUrl: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&w=600&q=80',
        activePlantingCount: 48,
    },
    {
        id: 'crop-013',
        name: 'Cucumber (Pipino)',
        botanicalName: 'Cucumis sativus (Green Globe F1)',
        category: 'FRUIT',
        idealSoil: 'LOAM',
        season: 'YEAR_ROUND',
        daysToHarvest: 60,
        waterReqMmPerWeek: 50,
        npkRequirement: { nitrogen: 100, phosphorus: 70, potassium: 140 },
        companionCropsGood: ['Corn', 'String Beans', 'Okra'],
        companionCropsBad: ['Potato'],
        imageUrl: 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?auto=format&fit=crop&w=600&q=80',
        activePlantingCount: 22,
    },
    {
        id: 'crop-014',
        name: 'Lettuce (Litsugas)',
        botanicalName: 'Lactuca sativa (General F1)',
        category: 'LEAFY',
        idealSoil: 'LOAM',
        season: 'WET',
        daysToHarvest: 45,
        waterReqMmPerWeek: 30,
        npkRequirement: { nitrogen: 120, phosphorus: 50, potassium: 80 },
        companionCropsGood: ['Carrot', 'Tomato', 'Onion'],
        companionCropsBad: ['Celery'],
        imageUrl: 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?auto=format&fit=crop&w=600&q=80',
        activePlantingCount: 19,
    },
    {
        id: 'crop-015',
        name: 'Watermelon (Pakwan)',
        botanicalName: 'Citrullus lanatus (Sweet Ruby F1)',
        category: 'FRUIT',
        idealSoil: 'SANDY',
        season: 'DRY',
        daysToHarvest: 85,
        waterReqMmPerWeek: 40,
        npkRequirement: { nitrogen: 90, phosphorus: 80, potassium: 150 },
        companionCropsGood: ['Radish', 'Corn'],
        companionCropsBad: ['Potato'],
        imageUrl: 'https://images.unsplash.com/photo-1587049352847-4a222e784d38?auto=format&fit=crop&w=600&q=80',
        activePlantingCount: 14,
    },
    {
        id: 'crop-016',
        name: 'Calamansi (Kalamansi)',
        botanicalName: 'Citrofortunella microcarpa',
        category: 'FRUIT',
        idealSoil: 'LOAM',
        season: 'YEAR_ROUND',
        daysToHarvest: 180,
        waterReqMmPerWeek: 50,
        npkRequirement: { nitrogen: 130, phosphorus: 70, potassium: 160 },
        companionCropsGood: ['Legumes', 'Coffee'],
        companionCropsBad: [],
        imageUrl: 'https://images.unsplash.com/photo-1534531141161-bc8144299a8b?auto=format&fit=crop&w=600&q=80',
        activePlantingCount: 30,
    },
];

export const MOCK_PESTS = [
    {
        id: 'pest-001',
        name: 'Fruit Borer / Corn Earworm',
        localName: 'Ubod ng Kamatis / Harabas',
        scientificName: 'Helicoverpa armigera',
        affectedCrops: ['Tomato', 'Eggplant', 'Corn', 'Okra', 'Bell Pepper'],
        category: 'Insect Pest',
        organicControl: 'Spray Neem Oil extract (30ml/L water) or Bacillus thuringiensis (Bt). Handpick caterpillars early morning.',
        chemicalControl: 'Apply DA-approved Chlorantraniliprole or Emamectin benzoate at early instar stage.',
        preventionTips: 'Practice crop rotation with non-host crops. Install yellow sticky traps.',
        imageUrl: 'https://images.unsplash.com/photo-1535083783855-76ae62b2914e?auto=format&fit=crop&w=600&q=80'
    },
    {
        id: 'pest-002',
        name: 'Tomato Leaf Curl Virus (TyLCV)',
        localName: 'Kulot sa Kamatis / Whitefly Disease',
        scientificName: 'Begomovirus (transmitted by Bemisia tabaci)',
        affectedCrops: ['Tomato', 'Bell Pepper', 'Squash'],
        category: 'Viral Disease',
        organicControl: 'Spray soapy water or Neem oil to target whitefly vector. Remove infected plants immediately.',
        chemicalControl: 'Control vector whiteflies with Imidacloprid or Thiamethoxam during seedling stage.',
        preventionTips: 'Use TyLCV-resistant varieties (e.g. Diamante Max F1). Install insect netting.',
        imageUrl: 'https://images.unsplash.com/photo-1528183429752-a97d0bf99b5a?auto=format&fit=crop&w=600&q=80'
    },
    {
        id: 'pest-003',
        name: 'Diamondback Moth',
        localName: 'Ulod sa Repolyo',
        scientificName: 'Plutella xylostella',
        affectedCrops: ['Cabbage', 'Pechay', 'Mustard'],
        category: 'Insect Pest',
        organicControl: 'Apply Bt (Bacillus thuringiensis) kurstaki strain every 5-7 days.',
        chemicalControl: 'Rotate Spinetoram foliar sprays to prevent pesticide resistance.',
        preventionTips: 'Use overhead sprinkler irrigation to disturb egg-laying adult moths.',
        imageUrl: 'https://images.unsplash.com/photo-1543946207-39bd91e70ca7?auto=format&fit=crop&w=600&q=80'
    },
    {
        id: 'pest-004',
        name: 'Onion Thrips',
        localName: 'Peste sa Sibuyas / Thrips',
        scientificName: 'Thrips tabaci',
        affectedCrops: ['Onion', 'Garlic', 'Cabbage'],
        category: 'Insect Pest',
        organicControl: 'Blue sticky card traps (20 traps/ha). Spray bio-pesticide Beauveria bassiana.',
        chemicalControl: 'Apply Abamectin or Fipronil in severe infestations during bulb establishment.',
        preventionTips: 'Maintain proper soil moisture. Avoid planting near older onion fields.',
        imageUrl: 'https://images.unsplash.com/photo-1584286595398-a59f21d313f5?auto=format&fit=crop&w=600&q=80'
    },
    {
        id: 'pest-005',
        name: 'Fall Armyworm',
        localName: 'Armyworm / Harabas sa Mais',
        scientificName: 'Spodoptera frugiperda',
        affectedCrops: ['Corn', 'String Beans', 'Cucumber'],
        category: 'Insect Pest',
        organicControl: 'Drop sand/ash mixed with Neem powder into corn whorls.',
        chemicalControl: 'Target whorls with Spinetoram or Methomyl sprays during early egg hatch.',
        preventionTips: 'Deep plowing after harvest to destroy pupae in soil.',
        imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80'
    },
    {
        id: 'pest-006',
        name: 'Powdery Mildew',
        localName: 'Pulbos sa Dahon ng Kalabasa',
        scientificName: 'Erysiphe cichoracearum',
        affectedCrops: ['Squash', 'Cucumber', 'Okra', 'Ampalaya'],
        category: 'Fungal Disease',
        organicControl: 'Foliar spray of 10% baking soda solution or diluted milk spray.',
        chemicalControl: 'Apply Potassium bicarbonate or Sulfur-based fungicide.',
        preventionTips: 'Ensure wider plant spacing for air circulation. Avoid overhead watering.',
        imageUrl: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?auto=format&fit=crop&w=600&q=80'
    }
];

export const MOCK_SOILS = [
    {
        soilType: 'LOAM',
        title: 'Loam Soil',
        localName: 'Lupang Luto / Ideal Loam',
        description: 'Dark, rich, crumbly soil with a balanced mixture of sand, silt, and clay.',
        characteristics: 'Excellent moisture retention with optimal internal drainage; rich in humus.',
        drainageSpeed: 'Moderate / Ideal (15–25 mm/hr)',
        phRange: '6.0 – 7.0',
        texture: 'Crumbly and soft when dry, forms a loose ball when moist.',
        bestCrops: ['Tomato', 'Eggplant', 'Bell Pepper', 'Carrot', 'Onion', 'Lettuce', 'Corn', 'Squash'],
        imageUrl: 'https://images.unsplash.com/photo-1585336261026-875a60a1c92f?auto=format&fit=crop&w=600&q=80',
        colorHex: '#3E2723'
    },
    {
        soilType: 'CLAY',
        title: 'Clay Soil',
        localName: 'Lupang Malagkit / Pula',
        description: 'Fine-textured soil composed of dense clay mineral particles.',
        characteristics: 'Holds abundant plant nutrients; high water capacity; slow to drain.',
        drainageSpeed: 'Slow (< 5 mm/hr)',
        phRange: '5.5 – 7.0',
        texture: 'Sticky and smooth when wet, forms hard clods when dry.',
        bestCrops: ['Eggplant', 'Okra', 'Kangkong', 'Squash', 'Corn'],
        imageUrl: 'https://images.unsplash.com/photo-1516253593875-bd7ba052fbc5?auto=format&fit=crop&w=600&q=80',
        colorHex: '#5D4037'
    },
    {
        soilType: 'SANDY',
        title: 'Sandy Soil',
        localName: 'Lupang Buhangin',
        description: 'Coarse-grained soil with large quartz particles. Highly porous and fast-draining.',
        characteristics: 'Warms up rapidly in dry season; excellent root penetration.',
        drainageSpeed: 'Fast (> 50 mm/hr)',
        phRange: '5.5 – 6.8',
        texture: 'Gritty and loose, cannot hold form when squeezed.',
        bestCrops: ['Carrot', 'Watermelon', 'Onion', 'Tomato', 'Radish'],
        imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
        colorHex: '#C6A700'
    },
    {
        soilType: 'SILTY',
        title: 'Silty Soil',
        localName: 'Lupang Banlik / River Silt',
        description: 'Smooth, fertile soil deposited by alluvial river beds.',
        characteristics: 'Very smooth texture; easily tilled; retains moisture efficiently.',
        drainageSpeed: 'Moderate (10–20 mm/hr)',
        phRange: '6.0 – 7.0',
        texture: 'Floury and smooth when dry, silky when moist.',
        bestCrops: ['Cabbage', 'Kangkong', 'Lettuce', 'String Beans', 'Pechay'],
        imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=600&q=80',
        colorHex: '#795548'
    },
    {
        soilType: 'PEATY',
        title: 'Peaty Soil',
        localName: 'Lupang Organiko / Peat',
        description: 'Dark, spongy soil high in decomposed organic plant materials.',
        characteristics: 'High organic content; rich in nitrogen; naturally acidic.',
        drainageSpeed: 'Moderate to Slow',
        phRange: '4.5 – 6.0',
        texture: 'Spongy, dark brown or black, lightweight.',
        bestCrops: ['Lettuce', 'Cabbage', 'Kangkong', 'Radish'],
        imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=600&q=80',
        colorHex: '#212121'
    },
    {
        soilType: 'CHALKY',
        title: 'Chalky Soil',
        localName: 'Lupang Apog / Alkaline',
        description: 'Light soil sitting over limestone bedrock. Rich in calcium carbonate.',
        characteristics: 'Alkaline pH; fast draining; benefits from regular organic matter.',
        drainageSpeed: 'Fast to Moderate',
        phRange: '7.0 – 8.0',
        texture: 'Stony or chalky white flecks throughout dry soil.',
        bestCrops: ['Okra', 'Corn', 'String Beans'],
        imageUrl: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=600&q=80',
        colorHex: '#9E9E9E'
    }
];

export const MOCK_DSS_RULES: DSSRule[] = [
    {
        id: 'dss-001',
        cropA: 'Carrot (Karot)',
        cropB: 'Tomato (Kamatis)',
        relationship: 'BENEFICIAL',
        reason: 'Tomatoes produce solanine which deters carrot rust flies; carrots loosen soil for deep tomato root growth.',
        daReferenceDoc: 'DA-BPI Companion Bulletin Vol 4',
    },
    {
        id: 'dss-002',
        cropA: 'Tomato (Kamatis)',
        cropB: 'Cabbage (Repolyo)',
        relationship: 'ANTAGONIST',
        reason: 'Both heavy nitrogen feeders competing for soil nutrients; high vulnerability to flea beetles.',
        daReferenceDoc: 'DA Agroforestry Manual Sec 3.2',
    },
    {
        id: 'dss-003',
        cropA: 'String Beans (Sitao)',
        cropB: 'Eggplant (Talong)',
        relationship: 'BENEFICIAL',
        reason: 'Legumes fix atmospheric nitrogen directly benefiting nitrogen-hungry eggplants.',
        daReferenceDoc: 'BPI Crop Rotation Protocol 2025',
    },
];

export const MOCK_FARMS: Farm[] = [
    {
        id: 'farm-001',
        farmerId: 'usr-001',
        farmerName: 'Jomarey D. Parreño',
        farmName: 'Murcia Organic Farm',
        soilType: 'LOAM',
        bedsCount: 14,
        createdAt: '2026-01-15T08:30:00Z',
    },
    {
        id: 'farm-002',
        farmerId: 'usr-002',
        farmerName: 'John Ryan R. Vasquez',
        farmName: 'Vasquez Highland Crops',
        soilType: 'LOAM',
        bedsCount: 22,
        createdAt: '2026-02-01T09:12:00Z',
    },
];



export const MOCK_BEDS: CropZone[] = [
    // Farm 001 - Murcia Organic Farm
    { id: 'zone-001', farmId: 'farm-001', cropZoneLabel: 'Plot A1 - Carrots', cropId: 'crop-001', cropName: 'Carrot (Karot)', x: 12, y: 12, width: 3, height: 3, growthStage: 3, plantedDate: '2026-06-01', expectedHarvestDate: '2026-08-15', healthScore: 94 },
    { id: 'zone-002', farmId: 'farm-001', cropZoneLabel: 'Plot A2 - Tomatoes', cropId: 'crop-004', cropName: 'Tomato (Kamatis)', x: 18, y: 12, width: 4, height: 3, growthStage: 2, plantedDate: '2026-06-15', expectedHarvestDate: '2026-09-02', healthScore: 88 },
    { id: 'zone-003', farmId: 'farm-001', cropZoneLabel: 'Plot B1 - Sitaw Beans', cropId: 'crop-002', cropName: 'String Beans (Sitaw)', x: 12, y: 18, width: 4, height: 4, growthStage: 4, plantedDate: '2026-05-20', expectedHarvestDate: '2026-07-30', healthScore: 98 },
    { id: 'zone-004', farmId: 'farm-001', cropZoneLabel: 'Plot B2 - Eggplant', cropId: 'crop-003', cropName: 'Eggplant (Talong)', x: 20, y: 18, width: 3, height: 3, growthStage: 1, plantedDate: '2026-07-10', expectedHarvestDate: '2026-10-08', healthScore: 90 },
    { id: 'zone-005', farmId: 'farm-001', cropZoneLabel: 'Plot C1 - Sweet Corn', cropId: 'crop-007', cropName: 'Sweet Corn (Mais)', x: 26, y: 12, width: 5, height: 4, growthStage: 3, plantedDate: '2026-06-05', expectedHarvestDate: '2026-08-20', healthScore: 95 },
    { id: 'zone-006', farmId: 'farm-001', cropZoneLabel: 'Plot C2 - Squash/Kalabasa', cropId: 'crop-006', cropName: 'Squash (Kalabasa)', x: 26, y: 20, width: 5, height: 5, growthStage: 2, plantedDate: '2026-06-18', expectedHarvestDate: '2026-09-10', healthScore: 82 },
    { id: 'zone-007', farmId: 'farm-001', cropZoneLabel: 'Plot D1 - Chili Pepper', cropId: 'crop-012', cropName: 'Chili Pepper (Sili)', x: 12, y: 26, width: 3, height: 3, growthStage: 4, plantedDate: '2026-05-15', expectedHarvestDate: '2026-08-01', healthScore: 91 },
    { id: 'zone-008', farmId: 'farm-001', cropZoneLabel: 'Plot D2 - Pechay Bed', cropId: 'crop-009', cropName: 'Pechay (Pechay)', x: 18, y: 26, width: 3, height: 3, growthStage: 2, plantedDate: '2026-07-01', expectedHarvestDate: '2026-08-10', healthScore: 78 },

    // Farm 002 - Vasquez Highland Crops
    { id: 'zone-101', farmId: 'farm-002', cropZoneLabel: 'Highland Cabbage Plot', cropId: 'crop-008', cropName: 'Cabbage (Repolyo)', x: 15, y: 15, width: 4, height: 4, growthStage: 3, plantedDate: '2026-06-10', expectedHarvestDate: '2026-08-25', healthScore: 96 },
    { id: 'zone-102', farmId: 'farm-002', cropZoneLabel: 'Ampalaya Trellis Zone', cropId: 'crop-010', cropName: 'Bitter Gourd (Ampalaya)', x: 22, y: 15, width: 4, height: 4, growthStage: 3, plantedDate: '2026-06-08', expectedHarvestDate: '2026-08-18', healthScore: 89 },
    { id: 'zone-103', farmId: 'farm-002', cropZoneLabel: 'Pipino Cucumber Bed', cropId: 'crop-013', cropName: 'Cucumber (Pipino)', x: 15, y: 22, width: 4, height: 3, growthStage: 1, plantedDate: '2026-07-05', expectedHarvestDate: '2026-09-05', healthScore: 92 },
];

export const MOCK_FEEDBACK: FeedbackItem[] = [
    {
        id: 'fb-101',
        farmerId: 'usr-001',
        farmerName: 'Jomarey D. Parreño',
        category: 'AGRONOMIC_QUERY',
        subject: 'Leaf yellowing on String Beans Plot B1',
        message: 'Noticeable yellow spots appearing on lower leaves after heavy rainfall last Tuesday. Should I increase Potassium or check drainage?',
        status: 'IN_PROGRESS',
        createdAt: '2026-07-27T14:22:00Z',
    },
    {
        id: 'fb-102',
        farmerId: 'usr-002',
        farmerName: 'John Ryan R. Vasquez',
        category: 'FEATURE_REQUEST',
        subject: 'Request for Weather Radar integration in DSS',
        message: 'It would be great to get automated warnings when rainfall prediction exceeds 50mm in Don Salvador Benedicto.',
        status: 'PENDING',
        createdAt: '2026-07-28T09:10:00Z',
    },
    {
        id: 'fb-103',
        farmerId: 'usr-003',
        farmerName: 'Jason B. Juanillo',
        category: 'BUG',
        subject: 'Offline sync badge delay on Android app',
        message: 'Completed tasks took 1 minute to reflect green checkmark when reconnecting to mobile data.',
        status: 'RESOLVED',
        createdAt: '2026-07-25T11:45:00Z',
        resolvedAt: '2026-07-26T16:00:00Z',
    },
];

export const MOCK_LOGS: SystemAuditLog[] = [
    {
        id: 'log-501',
        timestamp: '2026-07-29T11:20:00Z',
        adminEmail: 'admin@system.local',
        action: 'UPDATE_CROP_RULE',
        targetModule: 'DSS Rule Engine',
        details: 'Modified NPK ratio for Daucus carota (Carrot) based on DA 2026 guidelines.',
        status: 'SUCCESS',
        ipAddress: '112.198.75.12',
    },
    {
        id: 'log-502',
        timestamp: '2026-07-29T09:14:00Z',
        adminEmail: 'admin@system.local',
        action: 'USER_ROLE_CHANGE',
        targetModule: 'Farmer Management',
        details: 'Validated account for John Ryan R. Vasquez (Highland Farm).',
        status: 'SUCCESS',
        ipAddress: '112.198.75.12',
    },
    {
        id: 'log-503',
        timestamp: '2026-07-28T18:05:00Z',
        adminEmail: 'sys.bot@maptanim.ph',
        action: 'BACKUP_SYNC',
        targetModule: 'Database Cloud',
        details: 'Automated Supabase PostgreSQL snapshot completed (34 tables, 14MB).',
        status: 'SUCCESS',
        ipAddress: '10.0.4.18',
    },
];

export const MOCK_STATS: DashboardStats = {
    totalFarmers: 148,
    activeFarms: 132,
    totalPlots: 864,
    totalHarvestKgThisMonth: 3420,
    systemHealth: '99.98% Operational',
    monthlyYield: [
        { month: 'Jan', yieldKg: 2100, targetKg: 2000 },
        { month: 'Feb', yieldKg: 2450, targetKg: 2200 },
        { month: 'Mar', yieldKg: 2800, targetKg: 2500 },
        { month: 'Apr', yieldKg: 3100, targetKg: 2800 },
        { month: 'May', yieldKg: 2950, targetKg: 3000 },
        { month: 'Jun', yieldKg: 3300, targetKg: 3100 },
        { month: 'Jul', yieldKg: 3420, targetKg: 3300 },
    ],
    cropDistribution: [
        { category: 'Fruit Vegetables (Tomato/Talong)', value: 35, color: '#4caf50' },
        { category: 'Root Crops (Carrot)', value: 25, color: '#f59e0b' },
        { category: 'Podded (String Beans)', value: 20, color: '#0284c7' },
        { category: 'Leafy (Cabbage/Petchay)', value: 20, color: '#8b5cf6' },
    ],
    farmerRegistrations: [
        { date: 'Mon', count: 4 },
        { date: 'Tue', count: 7 },
        { date: 'Wed', count: 5 },
        { date: 'Thu', count: 9 },
        { date: 'Fri', count: 12 },
        { date: 'Sat', count: 8 },
        { date: 'Sun', count: 6 },
    ],
};


